apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  labels:
    component: servicemonitor
spec:
  selector:
    matchExpressions:
      - key: component
        operator: Exists
  targetLabels:
    - component
  endpoints:
  - port: prod-ui
    interval: 5s
  - port: prod-crawler
    interval: 5s
  namespaceSelector:
    matchNames:
      - prod
