apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: search-engine-ui
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      readinessProbe:
        httpGet:
          path: /
          port: 80
        failureThreshold: 3
        successThreshold: 1
        initialDelaySeconds: 20
        periodSeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate 