apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      annotations:
      labels:
        app: ui
    spec:
      containers:
      - name: search-engine-ui
        image: docker.pkg.github.com/cloud-nation/apps/ui:release-latest
        env:
            - name: RABBITMQ_DEFAULT_USER 
              value: $(NAMESPACE)-user
            - name: RABBITMQ_DEFAULT_PASS 
              value: $(NAMESPACE)-password