apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      annotations:
      labels:
        app: ui
    spec:
      containers:
      - name: search-engine-ui
        image: docker.pkg.github.com/cloud-nation/apps/ui:release-latest
        env:
          - name: MONGO
            value: develop-mongo-svc.dev.svc.cluster.local
          - name: MONGO_PORT
            value: "27017"
          - name: FLASK_APP
            value: ui.py
        ports:
        - name: prod-ui
          containerPort: 8000
          protocol: TCP