apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontend
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: frontend