apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-sm
  namespace: monitoring
spec:
  endpoints:
  - interval: 3s
    port: dev-ui
  namespaceSelector:
    matchNames:
    - dev
  selector:
    matchLabels:
      app: ui