apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-monitor
  labels:
    app: dev-ui-metrics
spec:
  namespaceSelector:
    matchNames:
      - develop-ui
  selector:
    matchLabels:
      app: ui
  endpoints:
  - port: dev-ui
    path: /metrics
    interval: 5s