apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui-monitor
  labels:
    component: ui
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      component: ui
  targetLabels:
    - component
  endpoints:
  - port: dev-ui
    path: /metrics
    interval: 5s