apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    component: ui
spec:
  selector:
    app: ui
  ports:
    - name: dev-ui
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontend
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: dev-ui
    nodePort: 30100
    port: 9090
    protocol: TCP
    targetPort: dev-ui
  selector:
    prometheus: frontend