apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scraping
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: prod-tenant
  source:
    path: prometheus-scraping/overlays/prod
    repoURL: https://github.com/cloud-nation/apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true