name: Build search engine crawler image

on:
    workflow_dispatch:
        inputs:
          tag:
            description: 'Image tag'
            required: false
            default: 'latest'
     
    push:
        branches: [ dev ]
        paths:
            - 'crawler-app/**'

    pull_request:
        branches: [ main, dev ]
        paths:
            - 'crawler-app/**'
  
jobs:
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # strategy:
      #   matrix:
      #     python-version: [2.7, 3.9]

      steps:
      - uses: actions/checkout@v2
      
      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python-version }}
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.5.10

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt','**/requirements-test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip 
            pip install -r ${{ github.workspace }}/crawler-app/requirements.txt -r ${{ github.workspace }}/crawler-app/requirements-test.txt
      
      - name: Code coverage
        run: | 
            cd ${{ github.workspace }}/crawler-app 
            coverage run -m unittest discover -s ${{ github.workspace }}/crawler-app/tests/
            coverage report --include ${{ github.workspace }}/crawler-app/crawler/crawler.py 

      # - name: Code analysis
      #   run: pylint simple ${{ github.workspace }}/crawler-app/crawler
            
      - name: Run Unittests
        run: |
            cd ${{ github.workspace }}/crawler-app
            python3 -m unittest discover -s ${{ github.workspace }}/crawler-app/tests/  

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CI_TOKEN }}

      - name: Build and Publish Docker Image
        shell: bash
        run: |
            if [ ${{ github.base_ref }} = main ]
            then 
              export IMAGETAG="docker.pkg.github.com/${{ github.repository }}/crawler:release-latest"
            else
              export IMAGETAG="docker.pkg.github.com/${{ github.repository }}/crawler:${{ github.sha }}"
            fi
            docker build ${{ github.workspace }}/crawler-app -t $IMAGETAG
            docker push $IMAGETAG